### ISSUE TITLE
custom transport in C# service

### ISSUE THREAD

**Issue by mbroadst** [Azure/amqpnetlite#171]
Hi, this is more of a question than an issue. As you may recall I have a custom transport written to communicate over a serial port, and I'm running into some issues/leaks when using it in an amqp client contained within a windows service.

First of all, are there any examples of using AMQP.Net Lite  inside a service that I might have missed online? I've looked around and found very little info here.

My service attempts to reinitialize the amqp client on any errors, while keeping the service itself running. My custom transport internally uses what I'm calling a `SerialStream`, which uses `CreateFile`/`ReadFile`/`WriteFile` in order to communicate across the serial port's character device, and more importantly the "read' side of the equation is using a long-running `Task` to poll the device for more incoming data.

What I'm finding is that occasionally when some error occurs, the service attempts reconnection and throws `EACCESSDENIED` errors because the previous `SerialStream` has not been properly disposed of (this is my current working theory). I have implemented `Dispose` for the `SerialStream`, which includes closing the `SafeFileHandle` as well as issuing a cancellation on the cancellation token source providing the token for the reader thread, however if `Dispose` is never called (which I cannot confirm at this point) then I believe I begin leaking handles, and worse yet creating multiple reader threads.

Is there any way to ensure these streams are explicitly cleaned up? I've been modeling my `SerialStream` after the `NamedPipeStream`, and I notice that in the `NamedPipeTransport` you don't actually do any explicit cleanup in the factory. I imagine named pipes would suffer the same consequences as my case, so does this indicate I'm failing to do some cleanup inside my `SerialStream` or does the example in this case omit important error handling for the sake of brevity?

**Comment by xinchen10** [comment]
When certain error occurs, the connection closes the transport after closing itself. Closing the transport is a non-blocking operation. It is initiated but not awaited. The transport layer also tries to flush queued buffers before disposing the IAsyncTransport implementation (SerialStream in your case). If the transport is slow, there might be a small window where connection is closed but the IAsyncTransport object is still open. The best way to confirm this is to take a process dump when the particular error occurs (it can be done by using windbg.exe and setting up StopOnException).

This is typically not a problem with TCP or other transports which allows multiple instances. It would become a problem if the actual transport allow only exclusive access. You can workaround this problem by adding a retry in your transport factory code. If the resource is still in use, delay 5 seconds and retry.

Regarding NamedPipeTransport, the PipeSteam is disposed in the ITransport.Close method, which is called after the everything is done or cleaned up. I also tried creating multiple connections using the same named pipe factory and address and it is working fine. It is an example, so it is certainly possible that some error conditions may not be handled appropriately.

Running inside a Windows service should not be an issue, especially in this case.

**Comment by mbroadst** [comment]
@xinchen10 so I'm periodically experiencing an error [here](https://github.com/Azure/amqpnetlite/blob/58472679f70796666ea639d82f6845ee0b3c0221/src/Framing/ProtocolHeader.cs#L39), most likely because the proxy has some dirty data in its buffers - however it's a good failure test here. I'm catching that exception in a code like the following:
```
try
{
    var remoteAddress = @"agent://@localhost/\\.\Global\test.agent";
    Open openFrame = new Open()
    {
        ContainerId = Guid.NewGuid().ToString(),
        HostName = Network.GetHostName(),
        IdleTimeOut = 60 * 1000,
        MaxFrameSize = 64 * 1024
    };

    connection = connectionFactory
        .CreateAsync(new Address(remoteAddress), openFrame, (c, o) => { })
        .GetAwaiter()
        .GetResult();

    session = new Session(connection);
    // do something with session
}
catch (Exception e)
{
    // do something with the exception
}
```

the actual exception looks like:
```
2016-11-11 21:12:33.5623 [Error] TestService.DoServiceStartup Amqp.AmqpException: ProtocolName Expect:AMQP Actual:
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestService.DoServiceStartup()Amqp.AmqpException: ProtocolName Expect:AMQP Actual:
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestService.DoServiceStartup()    at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

And `Dispose` is never called on the streams created internally from the factory. Furthermore the connection doesn't ever seem to get returned so I don't have access to the internal streams to dispose of them myself (as far as I can tell). This leaves me in a rut because now I can't actually access the file since some background resource lays claim to it still.

**Comment by xinchen10** [comment]
@mbroadst  You might be hitting this issue:
https://github.com/Azure/amqpnetlite/issues/166

The fix is committed to master but not in the released NuGet packages.

**Comment by mbroadst** [comment]
@xinchen10 hm okay I'll try to build master and see if that fixes my issue, thanks

**Comment by mbroadst** [comment]
@xinchen10 unfortunately the published fix doesn't seem to solve my problem. The issue can be pretty easily reproduced by connecting to some TCP server that writes junk data, rather than the correct AMQP header for the open performative.  The problem you referenced above relates to how errors are handled once the connection is established, but the one I'm running into happens _before_ that.

I think it's the correct behavior that it throws an exception because there is no active/open connection to even send a close frame back on, however, I still find myself in a position where explicit cleanup of my serial stream is not taking place.. Perhaps a better solution would be to catch the `ProtocolHeader.Create` exception, explicitly call `Close()` on the transport, and then rethrow the exception?

**Comment by xinchen10** [comment]
@mbroadst When ProtocolHeader.Create throws exception, the AsyncPump calls Connection.OnIoException which in turn calls OnEnded. Your transport Close method should be called in that method. I am setting up a repro with custom TCP transport to see if I can repro the issue.

**Comment by xinchen10** [comment]
@mbroadst it turns out that if exceptions are thrown from sasl negotiation, the transport close method is not called. I will submit a fix soon. You address string has a '@' character before the host name but it does not have any user info.

**Comment by mbroadst** [comment]
@xinchen10 yeah sorry I was afk for the morning, I was going to say this is done _before_ the `AsyncPump`. I cut the credentials out of my example, but yeah I'm definitely using sasl

**Comment by mbroadst** [comment]
@xinchen10 works! thanks for the fix, any idea on timeline for the 2.0.0 release?

**Comment by mbroadst** [comment]
@xinchen10 I think I ran into another issue while debugging the proxy. It looks like this [exception](https://github.com/Azure/amqpnetlite/blob/master/src/Framing/Reader.cs#L56) was thrown and the transport was also not closed (it's a bit difficult because I'm not getting a stack trace from within the awaiter)

**Comment by mbroadst** [comment]
@xinchen10 it turns out the guests were overwriting the new 2.0.0 build of AMQP.Net Lite I made with the old 1.2.0 dll :stuck_out_tongue_winking_eye: no issues, this definitely corrected the problem
