### ISSUE TITLE
Serialization does not handle circular type references

### ISSUE THREAD

**Issue by woppa684** [Azure/amqpnetlite#439]
I think the title is self-explanatory. Shortest example is something like the one below, but more complex examples are also possible of course (the circular dependency can be multiple levels deep). Just to be clear: The data (the values) does not have circular dependencies, only the types.

```cs
[AmqpContract]
class Group
{
    [AmqpMember]
    public string Name { get; set; }

    [AmqpMember]
    public List<Group> SubGroups { get; set; }
}
```

The serializer then crashes with a StackOverflowException
```
System.Private.CoreLib.dll!System.ModuleHandle.ResolveTypeHandleInternal(System.Reflection.RuntimeModule module, int typeToken, System.RuntimeTypeHandle[] typeInstantiationContext, System.RuntimeTypeHandle[] methodInstantiationContext)
System.Private.CoreLib.dll!System.Reflection.RuntimeModule.ResolveType(int metadataToken, System.Type[] genericTypeArguments, System.Type[] genericMethodArguments)
System.Private.CoreLib.dll!System.Reflection.CustomAttribute.FilterCustomAttributeRecord(System.Reflection.MetadataToken caCtorToken, System.Reflection.MetadataImport scope, System.Reflection.RuntimeModule decoratedModule, System.Reflection.MetadataToken decoratedToken, System.RuntimeType attributeFilterType, bool mustBeInheritable, ref System.RuntimeType.ListBuilder<object> derivedAttributes, out System.RuntimeType attributeType, out System.IRuntimeMethodInfo ctor, out bool ctorHasParameters, out bool isVarArg)
System.Private.CoreLib.dll!System.Reflection.CustomAttribute.AddCustomAttributes(ref System.RuntimeType.ListBuilder<object> attributes, System.Reflection.RuntimeModule decoratedModule, int decoratedMetadataToken, System.RuntimeType attributeFilterType, bool mustBeInheritable, System.RuntimeType.ListBuilder<object> derivedAttributes)
System.Private.CoreLib.dll!System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeModule decoratedModule, int decoratedMetadataToken, int pcaCount, System.RuntimeType attributeFilterType)
System.Private.CoreLib.dll!System.Reflection.CustomAttribute.GetCustomAttributes(System.RuntimeType type, System.RuntimeType caType, bool inherit)
System.Private.CoreLib.dll!System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo element, System.Type type, bool inherit)
System.Private.CoreLib.dll!System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo element, System.Type attributeType, bool inherit)
System.Private.CoreLib.dll!System.Reflection.CustomAttributeExtensions.GetCustomAttribute<Amqp.Serialization.AmqpContractAttribute>(System.Reflection.MemberInfo element, bool inherit)
Amqp.Serialization.dll!Amqp.Serialization.AmqpContractResolver.Amqp.Serialization.IContractResolver.Resolve(System.Type type)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CreateContractType(Amqp.Serialization.AmqpContract contract)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CreateContractType(Amqp.Serialization.AmqpContract contract)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CreateContractType(Amqp.Serialization.AmqpContract contract)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CreateContractType(Amqp.Serialization.AmqpContract contract)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CreateContractType(Amqp.Serialization.AmqpContract contract)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CreateContractType(Amqp.Serialization.AmqpContract contract)
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly)

etc...
```

The serialization package offers the opportunity to plug in a custom contract resolver but that doesn't help in this case since the error happens in the serializer itself. Making the serializer able to handle these kinds of dependencies or offering the opportunity to plug in a custom serializer would help.

A possible way to achieve this (I think, have not looked a lot into the source code yet) is to first construct a type registry and if the encountered type is already in the registry skip it.

**Comment by xinchen10** [comment]
We cannot support circular value references as it is not part of the amqp type system definition but circular type reference should be possible. The solution your proposed should work.

**Comment by woppa684** [comment]
Would you be interesed in a PR for this @xinchen10? I could make one of course but, because there are a number of ways to accomplish this, maybe you want to do this yourself?

**Comment by woppa684** [comment]
Does that commit solve my issue? Then it could be closed I would say. And can we then expect a release soon?

**Comment by xinchen10** [comment]
It should fix the issue you reported. A new version 2.4.1 is released.

**Comment by woppa684** [comment]
I've tried version 2.4.1 with the exact exampe I provided above and I still get a stackoverflow (albeit a slightly different stack)

```
System.Private.CoreLib.dll!System.Reflection.Emit.DynamicMethod.CreateDelegate(System.Type delegateType) Line 346	C#
Amqp.Serialization.dll!Amqp.Serialization.MethodAccessor.TypeMethodAccessor.TypeMethodAccessor(System.Reflection.MethodInfo methodInfo)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CompileCollectionTypes(System.Type type)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CompileNonContractTypes(System.Type type)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly, System.Collections.Generic.HashSet<System.Type> pendingTypes)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CreateContractType(Amqp.Serialization.AmqpContract contract, System.Collections.Generic.HashSet<System.Type> pendingTypes)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly, System.Collections.Generic.HashSet<System.Type> pendingTypes)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CompileCollectionTypes(System.Type type)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CompileNonContractTypes(System.Type type)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly, System.Collections.Generic.HashSet<System.Type> pendingTypes)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CreateContractType(Amqp.Serialization.AmqpContract contract, System.Collections.Generic.HashSet<System.Type> pendingTypes)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly, System.Collections.Generic.HashSet<System.Type> pendingTypes)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CompileCollectionTypes(System.Type type)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CompileNonContractTypes(System.Type type)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly, System.Collections.Generic.HashSet<System.Type> pendingTypes)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CreateContractType(Amqp.Serialization.AmqpContract contract, System.Collections.Generic.HashSet<System.Type> pendingTypes)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly, System.Collections.Generic.HashSet<System.Type> pendingTypes)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CompileCollectionTypes(System.Type type)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CompileNonContractTypes(System.Type type)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly, System.Collections.Generic.HashSet<System.Type> pendingTypes)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CreateContractType(Amqp.Serialization.AmqpContract contract, System.Collections.Generic.HashSet<System.Type> pendingTypes)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.GetOrCompileType(System.Type type, bool describedOnly, System.Collections.Generic.HashSet<System.Type> pendingTypes)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CompileCollectionTypes(System.Type type)	Unknown
Amqp.Serialization.dll!Amqp.Serialization.AmqpSerializer.CompileNonContractTypes(System.Type type)	Unknown
etc
```

I'm not sure what `CompileNonContractTypes` is doing in this stack trace, in the example every field has a contract, right? Looking at the tests you added, this exact example (with a type containing a list of its own type) is not present, only via 2 other types (not sure this is relevant). What also strikes me is that non-contract-types do not use the `pendingTypes` at all, is this on purpose?

I will dig a bit further, maybe I made a mistake, but I just wanted to let you know upofront.

**Comment by xinchen10** [comment]
The fix is incomplete. It doesn't your example well. I added a test case where a circular reference is created from a collection of a type in another type. I thought it would cover your case but it didn't. I need to make another change to support your case.

**Comment by xinchen10** [comment]
@woppa684 the bug should be fixed now. I added your test code as a unit test and it is working. Should have done that in the previous iteration.

**Comment by woppa684** [comment]
Thanks! Will there be a 2.4.2 release any time soon?

**Comment by xinchen10** [comment]
Release v2.4.2 is out.
